### ISSUE TITLE
Ghost Bus Logo Should Navigate to Home

### ISSUE THREAD

**Issue by JRisJunior** [chihacknight/ghost-buses-frontend#118]
Many websites that have an image or logo for the site in their headers often allow users to click them to navigate back to the home page. This functionality should be added to the Ghost Bus logo.

**Comment by fionatagious** [comment]
Hello! I'm ready to open a PR for this.

**Comment by fionatagious** [comment]
Apologies, I just read "May be fixed by #119" at the top of this page.
