### ISSUE TITLE
[Frontend] Set y-axis to autoscale on ratio plots

### ISSUE THREAD

**Issue by dcjohnson24** [chihacknight/ghost-buses-frontend#127]
![Image](https://github.com/chihacknight/ghost-buses-frontend/assets/36621602/88a96681-7e6d-4510-80ac-2c8aebce7358)

Y-axis needs to be autoscaled.

**Comment by KyleDolezal** [comment]
@dcjohnson24 May I please have context about how to reproduce the screenshotted issue? Do I need a particular route's graph or a particular screen resolution? Thank you.

**Comment by dcjohnson24** [comment]
Hey, you can view the issue by going to route 121 on the [map](https://ghostbuses.com/route-stats/121).
