### ISSUE TITLE
a11y considerations for frontend Accessibility Options

### ISSUE THREAD

**Issue by amy-corson** [chihacknight/ghost-buses-frontend#22]
Accessibility concerns including:

- [x] option to pause animation + hide animation for prefers-reduced-motion
- [x] alt text on every image
- [x] "skip to content" links
- [ ] #88
- [x] nav must have readable links
- [ ] #89
- [ ] #90
- [ ] #91
- [ ] #92
- [ ] #93
- [ ] #94

**Comment by hkier** [comment]
Closing this issue as the individual accessibility items each have their own issue

**Comment by hkier** [comment]
closing
