### ISSUE TITLE
[Bug] Map Display Seemingly Broken on OSX

### ISSUE THREAD

**Issue by SorenSpicknall** [chihacknight/ghost-buses-frontend#24]
Hey there, apologies for the out-of-nowhere issue - I've been keeping up with the project from afar, and when I noticed this on the prototype Laurie directed me to file an issue. Not sure if I just caught things in an in-between state while changes were being made, but [this is what the map view looks like for me](https://imgur.com/a/raC4BHO) across multiple browsers on OSX Monterey (12.5.1). It persists when the window size is reduced to a standard mobile aspect ratio. Hoping it's just an ephemeral issue while y'all work on your last pre-launch changes!

**Comment by ameliacorson** [comment]
Hi Soren! Thanks so so much for submitting this! VERY weird stuff. I tried replicating this bug with OSX Monterey as well, on a few different browsers, and I'm just not seeing it. Is it still showing up on your end?

**Comment by SorenSpicknall** [comment]
> Hi Soren! Thanks so so much for submitting this! VERY weird stuff. I tried replicating this bug with OSX Monterey as well, on a few different browsers, and I'm just not seeing it. Is it still showing up on your end?

Hey! After sticking around for about a day, the issue seems to have totally disappeared. I'll go ahead and close this for now, but I'll let you know if it comes back up at any point.
