### ISSUE TITLE
Incorrect bus ranking in modal

### ISSUE THREAD

**Issue by ameliacorson** [chihacknight/ghost-buses-frontend#25]
Bus ranking and percentile numbers are not matching up

- My suspicion is that there are more than 127 buses in the data and this should be updated 

![image](https://user-images.githubusercontent.com/92054473/199634588-e38f991f-98d6-4c99-a451-f7198873847d.png)

**Comment by mrscraps13** [comment]
So according to https://www.transitchicago.com/facts/
they mention 129 - ill try to echo into this a bit more!

**Comment by ameliacorson** [comment]
Oops!! This is closed! I completely forgot to update the board, that's my fault. @mrscraps13 
The issue is we only tract 124 of the buses, so updating the ghost bus modal to 124 solved the problem.
There are buses such as the BLS shuttle for example, that we do not have data for.
