### ISSUE TITLE
Strong text in buttons thickness

### ISSUE THREAD

**Issue by danielve4** [chihacknight/ghost-buses-frontend#27]
The text inside the `<strong>` tag in buttons is shown with the same thickness as text without the `strong` tag in Chrome.
Seems like the `font-weight` value 700 (normal button text) and `font-weight` value 900 (strong button text) have the same thickness in the Arial type used in Chrome.
Safari on MacOS and iOS is not affected.

Chrome:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/21179942/199652466-ffe36695-1375-4adc-a84e-264153748a3a.png">

Safari:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/21179942/199652524-069509f3-237c-4a84-9831-0a4e8999a093.png">

**Comment by hkier** [comment]
I have investigated this issue and find it unsubstantiated.  I have compared the button on three different browsers.  There are no differences seen.  I surmise this was a difference on the user's browsers with a different enlargement setting.  Closing the issue as invalid
