### ISSUE TITLE
QA pass: text updates before launch

### ISSUE THREAD

**Issue by lauriemerrell** [chihacknight/ghost-buses-frontend#30]
This is just a list of text edits based on a QA pass of the UI:

* On the home page, we say `129` bus lines but on the map page we say `127` -- is one of those the weekday-only number, maybe? Just wondering if maybe we should say "120+" or something more vague so we don't have to manually keep this up to date if we change the # of routes we're including
* On the `further reading` page, some articles have quotes around their titles and others don't -- I think either way is fine, but we should standardize?
* In the `links` in the footer, I think we stylize Chi Hack Night with spaces (not without spaces)
* Also in the footer, I think we could say GitHub repo (`H` capitalized)
* We had some updates on the methodology copy in the Google Doc -- if possible it would be good to use the updated version, let me know if I can help substitute that in?
* On the take action page, the RTA survey has closed so I think we should remove that one. For the others, if it's possible to make the linked text more substantive (so link the phrase `Commuters Take Action petition` instead of linking the word `here`), I believe that's an accessibility best practice

**Comment by ameliacorson** [comment]
Closed with https://github.com/chihacknight/ghost-buses-frontend/pull/32
