### ISSUE TITLE
Content resize with animation on mobile Chrome

### ISSUE THREAD

**Issue by danielve4** [chihacknight/ghost-buses-frontend#35]
The page content resizes every 7 seconds with the restart of the ghost bus animation on mobile Chrome (Android and simulated mobile on desktop Chrome)
This also resizes the modal when viewing any bus route.
![Animation](https://user-images.githubusercontent.com/21179942/201444778-7b2fb875-3d17-44ec-9d17-47a9039a3feb.gif)

**Comment by danielve4** [comment]
@amy-corson 
I found the cause of the content resize. From what I gather, it's the image of the group of people in the animation waiting for the bus, more specifically, the parent of the image `<div class="bus-stop-container">`. Removing the `width` style from that `div` element will prevent the resize but disrupt the overall animation. Will look further into a solution.

**Comment by amy-corson** [comment]
Closed with #44
