### ISSUE TITLE
Navigating directly to `/map` on prod gives a 404 error

### ISSUE THREAD

**Issue by ATranimal** [chihacknight/ghost-buses-frontend#36]
sweet project!
-----

** Description
navigating directly to https://ghostbuses.com/map on production gives a 404 error.

** Technical Specifications

This isn't an error with the react codebase as it works correctly on local, but probably a problem with the server configuration. Not sure if you're using something like nginx to handle routing server requests to the correct port, but it needs to be changes to send all /* routes to the react port as well? again not sure your configuration.

( I'm also happy to take a look, just couldn't find any information about joining a slack group or whatnot. either way, it would be good to have users be able to link `/map` )

**Comment by lauriemerrell** [comment]
Thanks @ATranimal ! Info on how to join the group is available here: https://github.com/chihacknight/breakout-groups/issues/217, and I came here to write up the exact same issue, thanks for already submitting!

**Comment by lauriemerrell** [comment]
Hoping this is closed by #37!
