### ISSUE TITLE
Search input should be the same width of the parent div

### ISSUE THREAD

**Issue by amy-corson** [chihacknight/ghost-buses-frontend#45]
When focused the search bar is noticeably shorter than the parent container - these could be the same width just to look nice!

![Screen Shot 2022-12-12 at 10 55 53 AM](https://user-images.githubusercontent.com/92054473/207106190-8ac9af98-7518-47fa-861a-e83dc10e1a76.png)

**Comment by Rishav1707** [comment]
I will like to work on this issue.

**Comment by amy-corson** [comment]
Closed with #48
