### ISSUE TITLE
Fix alignment on blockquote in home page

### ISSUE THREAD

**Issue by amy-corson** [chihacknight/ghost-buses-frontend#47]
The block quote is aligned left and also has a set width, which is looking a little wonky on smaller screen sizes, as shown below. This could either be aligned center or fixed in some other way.

![Screen Shot 2022-12-12 at 11 18 34 AM](https://user-images.githubusercontent.com/92054473/207111035-74175a6b-7a52-4b30-88a0-90e5937976ad.png)

**Comment by hkier** [comment]
There is an open PR for this #51.  However, since the PR was not merged when it was approved, it appears there have been some changes to the same files which created a merge conflict.  Those changes need to be research and resolved before this issue can proceed.

**Comment by hkier** [comment]
PR #86 has been created for this issue.
