### ISSUE TITLE
Condense site header vertically

### ISSUE THREAD

**Issue by smacmullan** [chihacknight/ghost-buses-frontend#55]
Site visitors have to scroll down before they see the map or read most of the content. Can we make the header take up less vertical space?

**Comment by hkier** [comment]
This is one alternative solution where a lot of the padding and margins have been removed.  Is this what is needed to resolve this issue or is more compression of the header area needed?
![Screenshot 2023-07-13 at 19-34-15 Ghost Bus by ChiHackNight](https://github.com/chihacknight/ghost-buses-frontend/assets/28713997/18f2843f-60e6-4295-a7bd-6577235d98de)

Also this is just a mock up, the actual version will have the proper layering so the "Ghost Buses" logo will appear on top of the cityscape.

**Comment by hkier** [comment]
I have completed the changes to the styling and will create a pr to merge the changes in.
