### ISSUE TITLE
Top 10 and Bottom 10 bus filter conflict with each other

### ISSUE THREAD

**Issue by smacmullan** [chihacknight/ghost-buses-frontend#57]
If you click "Top 10" and "Bottom 10" on the filter menu, instead of showing both sets of routes it shows none of them.

**Comment by ArslanYM** [comment]
![works](https://user-images.githubusercontent.com/104521101/230628535-356b0405-51f2-4196-97dd-d65715409faa.png)

@smacmullan It works correctly

**Comment by amy-corson** [comment]
Closed by #58
