### ISSUE TITLE
feat: There is no need to underline the zoom in and out button on hover. 

### ISSUE THREAD

**Issue by ArslanYM** [chihacknight/ghost-buses-frontend#70]
There is no need to underline the zoom in and out button on hover. 
![why](https://user-images.githubusercontent.com/104521101/230629318-b222ece4-c7e6-415d-908a-5d0597ca4023.png)

It doesnt suit the website and doesnt look aesthetic too.

**Comment by aortiz97-stack** [comment]
I'll work on this issue.

**Comment by hkier** [comment]
Looking through the repository, it appears this issue has been worked on but left in limbo.  PR #80 has been created BUT it does not have any deploys associated with it so there is no way to actually test it.  I am going to take over on this.  I will create a new branch, make the changes as shown, test them and then create a new PR so the change can be merged into the main.
