### ISSUE TITLE
[Frontend] Add start and end date fields to data.json

### ISSUE THREAD

**Issue by dcjohnson24** [chihacknight/ghost-buses-frontend#97]
The start and end date included in `data.json` will be used for displaying the date range on the map page.

**Comment by hkier** [comment]
The file name should not be changed as this will lead to future problems every time the data is updated.  This is contrary to our long term goal to decouple the data from the code.  As such, this issue either needs to be renamed to reflect the actual issue, which is the data does not include a date range or it needs to be closed.

**Comment by dcjohnson24** [comment]
Thanks for catching this. I've renamed the issue.

**Comment by lauriemerrell** [comment]
Closed 2nd time by #107
